export const FETCH_RANDOM_PHOTOS_SUCCESS = "FETCH_RANDOM_PHOTOS_SUCCESS";
export const FETCH_RANDOM_PHOTOS_FAILURE = "FETCH_RANDOM_PHOTOS_FAILURE";
export const FETCH_INFINITE_PHOTOS_SUCCESS = "FETCH_INFINITE_PHOTOS_SUCCESS";
export const FETCH_INFINITE_PHOTOS_FAILURE = "FETCH_INFINITE_PHOTOS_FAILURE";
