export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_PHOTOS_SUCCESS = "FETCH_USER_PHOTOS_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";
export const FETCH_USER_PHOTOS_FAILURE = "FETCH_USER_PHOTOS_FAILURE";
export const GET_USER_NEXT_PHOTOS_SUCCESS = "GET_USER_NEXT_PHOTOS_SUCCESS";
export const GET_USER_NEXT_PHOTOS_FAILURE = "GET_USER_NEXT_PHOTOS_FAILURE";
export const NEXT_PHOTO_LOADING = "NEXT_PHOTO_LOADING";
export const CLEAR_USER = "CLEAR_USER";
